# Site settings
title: Ronan
email: zzkkugou@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  心若有桃源，何处不是水云间。
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://zhuangzaiku.github.io" # the base hostname & protocol for your site
twitter_username: Ronan
github_username:  zhuangzaiku

# Build settings
markdown: kramdown
